// ============================================================
// pokemon-list.js — Données partagées entre index.html et team.html
// Ce fichier expose :
//   - POKEMON_LIST  : liste de tous les Pokémon du jeu
//   - translateType : fonction de traduction EN → FR des types
// ============================================================

// ============================================================
// 1. LISTE DES POKÉMON DE POKÉMON CHAMPIONS
//    Chaque entrée contient :
//    - id     : numéro du Pokédex
//    - slug   : identifiant PokéAPI pour cette forme spécifique
//    - nomFr  : nom français à afficher
//    - forme  : "base", "mega", "regional" ou "special"
// ============================================================
const POKEMON_LIST = [
  // --- Génération 1 ---
  { id: 3,   slug: "venusaur",              nomFr: "Florizarre",                          forme: "base"     },
  { id: 3,   slug: "venusaur-mega",          nomFr: "Méga-Florizarre",                     forme: "mega"     },
  { id: 6,   slug: "charizard",              nomFr: "Dracaufeu",                           forme: "base"     },
  { id: 6,   slug: "charizard-mega-x",       nomFr: "Méga-Dracaufeu X",                    forme: "mega"     },
  { id: 6,   slug: "charizard-mega-y",       nomFr: "Méga-Dracaufeu Y",                    forme: "mega"     },
  { id: 9,   slug: "blastoise",              nomFr: "Tortank",                             forme: "base"     },
  { id: 9,   slug: "blastoise-mega",         nomFr: "Méga-Tortank",                        forme: "mega"     },
  { id: 15,  slug: "beedrill",               nomFr: "Dardargnan",                          forme: "base"     },
  { id: 15,  slug: "beedrill-mega",          nomFr: "Méga-Dardargnan",                     forme: "mega"     },
  { id: 18,  slug: "pidgeot",                nomFr: "Roucarnage",                          forme: "base"     },
  { id: 18,  slug: "pidgeot-mega",           nomFr: "Méga-Roucarnage",                     forme: "mega"     },
  { id: 24,  slug: "arbok",                  nomFr: "Arbok",                               forme: "base"     },
  { id: 25,  slug: "pikachu",                nomFr: "Pikachu",                             forme: "base"     },
  { id: 26,  slug: "raichu",                 nomFr: "Raichu",                              forme: "base"     },
  { id: 26,  slug: "raichu-alola",           nomFr: "Raichu Forme d'Alola",                forme: "regional" },
  { id: 36,  slug: "clefable",               nomFr: "Mélodelfe",                           forme: "base"     },
  { id: 36,  slug: "clefable-mega",          nomFr: "Méga-Mélodelfe",                      forme: "mega"     },
  { id: 38,  slug: "ninetales",              nomFr: "Feunard",                             forme: "base"     },
  { id: 38,  slug: "ninetales-alola",        nomFr: "Feunard Forme d'Alola",               forme: "regional" },
  { id: 59,  slug: "arcanine",               nomFr: "Arcanin",                             forme: "base"     },
  { id: 59,  slug: "arcanine-hisui",         nomFr: "Arcanin Forme de Hisui",              forme: "regional" },
  { id: 65,  slug: "alakazam",               nomFr: "Alakazam",                            forme: "base"     },
  { id: 65,  slug: "alakazam-mega",          nomFr: "Méga-Alakazam",                       forme: "mega"     },
  { id: 68,  slug: "machamp",                nomFr: "Mackogneur",                          forme: "base"     },
  { id: 71,  slug: "victreebel",             nomFr: "Empiflor",                            forme: "base"     },
  { id: 71,  slug: "victreebel-mega",        nomFr: "Méga-Empiflor",                       forme: "mega"     },
  { id: 80,  slug: "slowbro",                nomFr: "Flagadoss",                           forme: "base"     },
  { id: 80,  slug: "slowbro-mega",           nomFr: "Méga-Flagadoss",                      forme: "mega"     },
  { id: 80,  slug: "slowbro-galar",          nomFr: "Flagadoss Forme de Galar",            forme: "regional" },
  { id: 94,  slug: "gengar",                 nomFr: "Ectoplasma",                          forme: "base"     },
  { id: 94,  slug: "gengar-mega",            nomFr: "Méga-Ectoplasma",                     forme: "mega"     },
  { id: 115, slug: "kangaskhan",             nomFr: "Kangourex",                           forme: "base"     },
  { id: 115, slug: "kangaskhan-mega",        nomFr: "Méga-Kangourex",                      forme: "mega"     },
  { id: 121, slug: "starmie",                nomFr: "Staross",                             forme: "base"     },
  { id: 121, slug: "starmie-mega",           nomFr: "Méga-Staross",                        forme: "mega"     },
  { id: 127, slug: "pinsir",                 nomFr: "Scarabrute",                          forme: "base"     },
  { id: 127, slug: "pinsir-mega",            nomFr: "Méga-Scarabrute",                     forme: "mega"     },
  { id: 128, slug: "tauros",                 nomFr: "Tauros",                              forme: "base"     },
  { id: 128, slug: "tauros-paldea-combat",   nomFr: "Tauros Paldea Race Combative",        forme: "regional" },
  { id: 128, slug: "tauros-paldea-blaze",    nomFr: "Tauros Paldea Race Flamboyante",      forme: "regional" },
  { id: 128, slug: "tauros-paldea-aqua",     nomFr: "Tauros Paldea Race Aquatique",        forme: "regional" },
  { id: 130, slug: "gyarados",               nomFr: "Léviator",                            forme: "base"     },
  { id: 130, slug: "gyarados-mega",          nomFr: "Méga-Léviator",                       forme: "mega"     },
  { id: 132, slug: "ditto",                  nomFr: "Métamorph",                           forme: "base"     },
  { id: 134, slug: "vaporeon",               nomFr: "Aquali",                              forme: "base"     },
  { id: 135, slug: "jolteon",                nomFr: "Voltali",                             forme: "base"     },
  { id: 136, slug: "flareon",                nomFr: "Pyroli",                              forme: "base"     },
  { id: 142, slug: "aerodactyl",             nomFr: "Ptéra",                               forme: "base"     },
  { id: 142, slug: "aerodactyl-mega",        nomFr: "Méga-Ptéra",                          forme: "mega"     },
  { id: 143, slug: "snorlax",                nomFr: "Ronflex",                             forme: "base"     },
  { id: 149, slug: "dragonite",              nomFr: "Dracolosse",                          forme: "base"     },
  { id: 149, slug: "dragonite-mega",         nomFr: "Méga-Dracolosse",                     forme: "mega"     },
  // --- Génération 2 ---
  { id: 154, slug: "meganium",               nomFr: "Méganium",                            forme: "base"     },
  { id: 154, slug: "meganium-mega",          nomFr: "Méga-Méganium",                       forme: "mega"     },
  { id: 157, slug: "typhlosion",             nomFr: "Typhlosion",                          forme: "base"     },
  { id: 157, slug: "typhlosion-hisui",       nomFr: "Typhlosion Forme de Hisui",           forme: "regional" },
  { id: 160, slug: "feraligatr",             nomFr: "Aligatueur",                          forme: "base"     },
  { id: 160, slug: "feraligatr-mega",        nomFr: "Méga-Aligatueur",                     forme: "mega"     },
  { id: 168, slug: "ariados",                nomFr: "Migalos",                             forme: "base"     },
  { id: 181, slug: "ampharos",               nomFr: "Pharamp",                             forme: "base"     },
  { id: 181, slug: "ampharos-mega",          nomFr: "Méga-Pharamp",                        forme: "mega"     },
  { id: 184, slug: "azumarill",              nomFr: "Azumarill",                           forme: "base"     },
  { id: 186, slug: "politoed",               nomFr: "Tarpaud",                             forme: "base"     },
  { id: 196, slug: "espeon",                 nomFr: "Mentali",                             forme: "base"     },
  { id: 197, slug: "umbreon",                nomFr: "Noctali",                             forme: "base"     },
  { id: 199, slug: "slowking",               nomFr: "Roigada",                             forme: "base"     },
  { id: 199, slug: "slowking-galar",         nomFr: "Roigada Forme de Galar",              forme: "regional" },
  { id: 205, slug: "forretress",             nomFr: "Foretress",                           forme: "base"     },
  { id: 208, slug: "steelix",                nomFr: "Steelix",                             forme: "base"     },
  { id: 208, slug: "steelix-mega",           nomFr: "Méga-Steelix",                        forme: "mega"     },
  { id: 212, slug: "scizor",                 nomFr: "Cizayox",                             forme: "base"     },
  { id: 212, slug: "scizor-mega",            nomFr: "Méga-Cizayox",                        forme: "mega"     },
  { id: 214, slug: "heracross",              nomFr: "Scarhino",                            forme: "base"     },
  { id: 214, slug: "heracross-mega",         nomFr: "Méga-Scarhino",                       forme: "mega"     },
  { id: 227, slug: "skarmory",               nomFr: "Airmure",                             forme: "base"     },
  { id: 227, slug: "skarmory-mega",          nomFr: "Méga-Airmure",                        forme: "mega"     },
  { id: 229, slug: "houndoom",               nomFr: "Démolosse",                           forme: "base"     },
  { id: 229, slug: "houndoom-mega",          nomFr: "Méga-Démolosse",                      forme: "mega"     },
  { id: 248, slug: "tyranitar",              nomFr: "Tyranocif",                           forme: "base"     },
  { id: 248, slug: "tyranitar-mega",         nomFr: "Méga-Tyranocif",                      forme: "mega"     },
  // --- Génération 3 ---
  { id: 279, slug: "pelipper",               nomFr: "Bekipan",                             forme: "base"     },
  { id: 282, slug: "gardevoir",              nomFr: "Gardevoir",                           forme: "base"     },
  { id: 282, slug: "gardevoir-mega",         nomFr: "Méga-Gardevoir",                      forme: "mega"     },
  { id: 302, slug: "sableye",                nomFr: "Ténéfix",                             forme: "base"     },
  { id: 302, slug: "sableye-mega",           nomFr: "Méga-Ténéfix",                        forme: "mega"     },
  { id: 306, slug: "aggron",                 nomFr: "Galeking",                            forme: "base"     },
  { id: 306, slug: "aggron-mega",            nomFr: "Méga-Galeking",                       forme: "mega"     },
  { id: 308, slug: "medicham",               nomFr: "Charmina",                            forme: "base"     },
  { id: 308, slug: "medicham-mega",          nomFr: "Méga-Charmina",                       forme: "mega"     },
  { id: 310, slug: "manectric",              nomFr: "Élecsprint",                          forme: "base"     },
  { id: 310, slug: "manectric-mega",         nomFr: "Méga-Élecsprint",                     forme: "mega"     },
  { id: 319, slug: "sharpedo",               nomFr: "Sharpedo",                            forme: "base"     },
  { id: 319, slug: "sharpedo-mega",          nomFr: "Méga-Sharpedo",                       forme: "mega"     },
  { id: 323, slug: "camerupt",               nomFr: "Camérupt",                            forme: "base"     },
  { id: 323, slug: "camerupt-mega",          nomFr: "Méga-Camérupt",                       forme: "mega"     },
  { id: 324, slug: "torkoal",                nomFr: "Chartor",                             forme: "base"     },
  { id: 334, slug: "altaria",                nomFr: "Altaria",                             forme: "base"     },
  { id: 334, slug: "altaria-mega",           nomFr: "Méga-Altaria",                        forme: "mega"     },
  { id: 350, slug: "milotic",                nomFr: "Milobellus",                          forme: "base"     },
  { id: 351, slug: "castform",               nomFr: "Morphéo",                             forme: "base"     },
  { id: 351, slug: "castform-sunny",         nomFr: "Morphéo Forme Solaire",               forme: "special"  },
  { id: 351, slug: "castform-rainy",         nomFr: "Morphéo Forme Eau de Pluie",          forme: "special"  },
  { id: 351, slug: "castform-snowy",         nomFr: "Morphéo Forme Blizzard",              forme: "special"  },
  { id: 354, slug: "banette",                nomFr: "Branette",                            forme: "base"     },
  { id: 354, slug: "banette-mega",           nomFr: "Méga-Branette",                       forme: "mega"     },
  { id: 358, slug: "chimecho",               nomFr: "Éoko",                                forme: "base"     },
  { id: 358, slug: "chimecho-mega",          nomFr: "Méga-Éoko",                           forme: "mega"     },
  { id: 359, slug: "absol",                  nomFr: "Absol",                               forme: "base"     },
  { id: 359, slug: "absol-mega",             nomFr: "Méga-Absol",                          forme: "mega"     },
  { id: 362, slug: "glalie",                 nomFr: "Oniglali",                            forme: "base"     },
  { id: 362, slug: "glalie-mega",            nomFr: "Méga-Oniglali",                       forme: "mega"     },
  // --- Génération 4 ---
  { id: 389, slug: "torterra",               nomFr: "Torterra",                            forme: "base"     },
  { id: 392, slug: "infernape",              nomFr: "Simiabraz",                           forme: "base"     },
  { id: 395, slug: "empoleon",               nomFr: "Pingoléon",                           forme: "base"     },
  { id: 405, slug: "luxray",                 nomFr: "Luxray",                              forme: "base"     },
  { id: 407, slug: "roserade",               nomFr: "Roserade",                            forme: "base"     },
  { id: 409, slug: "rampardos",              nomFr: "Charkos",                             forme: "base"     },
  { id: 411, slug: "bastiodon",              nomFr: "Bastiodon",                           forme: "base"     },
  { id: 428, slug: "lopunny",                nomFr: "Lockpin",                             forme: "base"     },
  { id: 428, slug: "lopunny-mega",           nomFr: "Méga-Lockpin",                        forme: "mega"     },
  { id: 442, slug: "spiritomb",              nomFr: "Spiritomb",                           forme: "base"     },
  { id: 445, slug: "garchomp",               nomFr: "Carchacrok",                          forme: "base"     },
  { id: 445, slug: "garchomp-mega",          nomFr: "Méga-Carchacrok",                     forme: "mega"     },
  { id: 448, slug: "lucario",                nomFr: "Lucario",                             forme: "base"     },
  { id: 448, slug: "lucario-mega",           nomFr: "Méga-Lucario",                        forme: "mega"     },
  { id: 450, slug: "hippowdon",              nomFr: "Hippodocus",                          forme: "base"     },
  { id: 454, slug: "toxicroak",              nomFr: "Coatox",                              forme: "base"     },
  { id: 460, slug: "abomasnow",              nomFr: "Blizzaroi",                           forme: "base"     },
  { id: 460, slug: "abomasnow-mega",         nomFr: "Méga-Blizzaroi",                      forme: "mega"     },
  { id: 461, slug: "weavile",                nomFr: "Dimoret",                             forme: "base"     },
  { id: 464, slug: "rhyperior",              nomFr: "Rhinastoc",                           forme: "base"     },
  { id: 470, slug: "leafeon",                nomFr: "Phyllali",                            forme: "base"     },
  { id: 471, slug: "glaceon",                nomFr: "Givrali",                             forme: "base"     },
  { id: 472, slug: "gliscor",                nomFr: "Scorvol",                             forme: "base"     },
  { id: 473, slug: "mamoswine",              nomFr: "Mammochon",                           forme: "base"     },
  { id: 475, slug: "gallade",                nomFr: "Gallame",                             forme: "base"     },
  { id: 475, slug: "gallade-mega",           nomFr: "Méga-Gallame",                        forme: "mega"     },
  { id: 478, slug: "froslass",               nomFr: "Momartik",                            forme: "base"     },
  { id: 478, slug: "froslass-mega",          nomFr: "Méga-Momartik",                       forme: "mega"     },
  { id: 479, slug: "rotom",                  nomFr: "Motisma",                             forme: "base"     },
  { id: 479, slug: "rotom-heat",             nomFr: "Motisma Chaleur",                     forme: "special"  },
  { id: 479, slug: "rotom-wash",             nomFr: "Motisma Lavage",                      forme: "special"  },
  { id: 479, slug: "rotom-frost",            nomFr: "Motisma Froid",                       forme: "special"  },
  { id: 479, slug: "rotom-fan",              nomFr: "Motisma Hélice",                      forme: "special"  },
  { id: 479, slug: "rotom-mow",              nomFr: "Motisma Tonte",                       forme: "special"  },
  // --- Génération 5 ---
  { id: 497, slug: "serperior",              nomFr: "Majaspic",                            forme: "base"     },
  { id: 500, slug: "emboar",                 nomFr: "Roitiflam",                           forme: "base"     },
  { id: 500, slug: "emboar-mega",            nomFr: "Méga-Roitiflam",                      forme: "mega"     },
  { id: 503, slug: "samurott",               nomFr: "Clamiral",                            forme: "base"     },
  { id: 503, slug: "samurott-hisui",         nomFr: "Clamiral Forme de Hisui",             forme: "regional" },
  { id: 505, slug: "watchog",                nomFr: "Miradar",                             forme: "base"     },
  { id: 510, slug: "liepard",                nomFr: "Léopardus",                           forme: "base"     },
  { id: 512, slug: "simisage",               nomFr: "Feuiloutan",                          forme: "base"     },
  { id: 514, slug: "simisear",               nomFr: "Flamoutan",                           forme: "base"     },
  { id: 516, slug: "simipour",               nomFr: "Flotoutan",                           forme: "base"     },
  { id: 530, slug: "excadrill",              nomFr: "Minotaupe",                           forme: "base"     },
  { id: 530, slug: "excadrill-mega",         nomFr: "Méga-Minotaupe",                      forme: "mega"     },
  { id: 531, slug: "audino",                 nomFr: "Nanméouïe",                           forme: "base"     },
  { id: 531, slug: "audino-mega",            nomFr: "Méga-Nanméouïe",                      forme: "mega"     },
  { id: 534, slug: "conkeldurr",             nomFr: "Bétochef",                            forme: "base"     },
  { id: 547, slug: "whimsicott",             nomFr: "Farfaduvet",                          forme: "base"     },
  { id: 553, slug: "krookodile",             nomFr: "Crocorible",                          forme: "base"     },
  { id: 563, slug: "cofagrigus",             nomFr: "Tutankafer",                          forme: "base"     },
  { id: 569, slug: "garbodor",               nomFr: "Miasmax",                             forme: "base"     },
  { id: 571, slug: "zoroark",                nomFr: "Zoroark",                             forme: "base"     },
  { id: 571, slug: "zoroark-hisui",          nomFr: "Zoroark Forme de Hisui",              forme: "regional" },
  { id: 579, slug: "reuniclus",              nomFr: "Symbios",                             forme: "base"     },
  { id: 584, slug: "vanilluxe",              nomFr: "Sorbouboul",                          forme: "base"     },
  { id: 587, slug: "emolga",                 nomFr: "Emolga",                              forme: "base"     },
  { id: 609, slug: "chandelure",             nomFr: "Lugulabre",                           forme: "base"     },
  { id: 609, slug: "chandelure-mega",        nomFr: "Méga-Lugulabre",                      forme: "mega"     },
  { id: 614, slug: "beartic",                nomFr: "Polagriffe",                          forme: "base"     },
  { id: 618, slug: "stunfisk",               nomFr: "Limonde",                             forme: "base"     },
  { id: 618, slug: "stunfisk-galar",         nomFr: "Limonde Forme de Galar",              forme: "regional" },
  { id: 623, slug: "golurk",                 nomFr: "Golemastoc",                          forme: "base"     },
  { id: 623, slug: "golurk-mega",            nomFr: "Méga-Golemastoc",                     forme: "mega"     },
  { id: 635, slug: "hydreigon",              nomFr: "Trioxhydre",                          forme: "base"     },
  { id: 637, slug: "volcarona",              nomFr: "Pyrax",                               forme: "base"     },
  // --- Génération 6 ---
  { id: 652, slug: "chesnaught",             nomFr: "Blindépique",                         forme: "base"     },
  { id: 652, slug: "chesnaught-mega",        nomFr: "Méga-Blindépique",                    forme: "mega"     },
  { id: 655, slug: "delphox",                nomFr: "Goupelin",                            forme: "base"     },
  { id: 655, slug: "delphox-mega",           nomFr: "Méga-Goupelin",                       forme: "mega"     },
  { id: 658, slug: "greninja",               nomFr: "Amphinobi",                           forme: "base"     },
  { id: 658, slug: "greninja-mega",          nomFr: "Méga-Amphinobi",                      forme: "mega"     },
  { id: 660, slug: "diggersby",              nomFr: "Excavarenne",                         forme: "base"     },
  { id: 663, slug: "talonflame",             nomFr: "Flambusard",                          forme: "base"     },
  { id: 666, slug: "vivillon",               nomFr: "Prismillon Motif Blizzard",           forme: "special"  },
  { id: 666, slug: "vivillon-polar",         nomFr: "Prismillon Motif Banquise",           forme: "special"  },
  { id: 666, slug: "vivillon-tundra",        nomFr: "Prismillon Motif Glace",              forme: "special"  },
  { id: 666, slug: "vivillon-continental",   nomFr: "Prismillon Motif Continent",          forme: "special"  },
  { id: 666, slug: "vivillon-garden",        nomFr: "Prismillon Motif Verdure",            forme: "special"  },
  { id: 666, slug: "vivillon-elegant",       nomFr: "Prismillon Motif Monarchie",          forme: "special"  },
  { id: 666, slug: "vivillon-meadow",        nomFr: "Prismillon Motif Floraison",          forme: "special"  },
  { id: 666, slug: "vivillon-modern",        nomFr: "Prismillon Motif Métropole",          forme: "special"  },
  { id: 666, slug: "vivillon-marine",        nomFr: "Prismillon Motif Rivage",             forme: "special"  },
  { id: 666, slug: "vivillon-archipelago",   nomFr: "Prismillon Motif Archipel",           forme: "special"  },
  { id: 666, slug: "vivillon-high-plains",   nomFr: "Prismillon Motif Sécheresse",         forme: "special"  },
  { id: 666, slug: "vivillon-sandstorm",     nomFr: "Prismillon Motif Sable",              forme: "special"  },
  { id: 666, slug: "vivillon-river",         nomFr: "Prismillon Motif Delta",              forme: "special"  },
  { id: 666, slug: "vivillon-monsoon",       nomFr: "Prismillon Motif Cyclone",            forme: "special"  },
  { id: 666, slug: "vivillon-savanna",       nomFr: "Prismillon Motif Mangrove",           forme: "special"  },
  { id: 666, slug: "vivillon-sun",           nomFr: "Prismillon Motif Zénith",             forme: "special"  },
  { id: 666, slug: "vivillon-ocean",         nomFr: "Prismillon Motif Soleil Levant",      forme: "special"  },
  { id: 666, slug: "vivillon-jungle",        nomFr: "Prismillon Motif Jungle",             forme: "special"  },
  { id: 666, slug: "vivillon-fancy",         nomFr: "Prismillon Motif Fantaisie",          forme: "special"  },
  { id: 666, slug: "vivillon-poke-ball",     nomFr: "Prismillon Motif Poké Ball",          forme: "special"  },
  { id: 670, slug: "floette-eternal",        nomFr: "Floette Éternelle",                   forme: "special"  },
  { id: 670, slug: "floette-mega",           nomFr: "Méga-Floette",                        forme: "mega"     },
  { id: 671, slug: "florges",                nomFr: "Florges Fleur Rouge",                 forme: "base"     },
  { id: 671, slug: "florges-yellow",         nomFr: "Florges Fleur Jaune",                 forme: "special"  },
  { id: 671, slug: "florges-orange",         nomFr: "Florges Fleur Orange",                forme: "special"  },
  { id: 671, slug: "florges-blue",           nomFr: "Florges Fleur Bleue",                 forme: "special"  },
  { id: 671, slug: "florges-white",          nomFr: "Florges Fleur Blanche",               forme: "special"  },
  { id: 675, slug: "pangoro",                nomFr: "Pandarbare",                          forme: "base"     },
  { id: 676, slug: "furfrou",                nomFr: "Couafarel Forme Sauvage",             forme: "base"     },
  { id: 676, slug: "furfrou-heart",          nomFr: "Couafarel Coupe Coeur",               forme: "special"  },
  { id: 676, slug: "furfrou-star",           nomFr: "Couafarel Coupe Etoile",              forme: "special"  },
  { id: 676, slug: "furfrou-diamond",        nomFr: "Couafarel Coupe Diamant",             forme: "special"  },
  { id: 676, slug: "furfrou-debutante",      nomFr: "Couafarel Coupe Demoiselle",          forme: "special"  },
  { id: 676, slug: "furfrou-matron",         nomFr: "Couafarel Coupe Madame",              forme: "special"  },
  { id: 676, slug: "furfrou-dandy",          nomFr: "Couafarel Coupe Monsieur",            forme: "special"  },
  { id: 676, slug: "furfrou-lareine",        nomFr: "Couafarel Coupe Reine",               forme: "special"  },
  { id: 676, slug: "furfrou-kabuki",         nomFr: "Couafarel Coupe Kabuki",              forme: "special"  },
  { id: 676, slug: "furfrou-pharaoh",        nomFr: "Couafarel Coupe Pharaon",             forme: "special"  },
  { id: 678, slug: "meowstic-male",          nomFr: "Mistigrix Male",                      forme: "base"     },
  { id: 678, slug: "meowstic-female",        nomFr: "Mistigrix Femelle",                   forme: "special"  },
  { id: 678, slug: "meowstic-mega",          nomFr: "Mega-Mistigrix",                      forme: "mega"     },
  { id: 681, slug: "aegislash-shield",       nomFr: "Exagide Forme Parade",                forme: "base"     },
  { id: 681, slug: "aegislash-blade",        nomFr: "Exagide Forme Assaut",                forme: "special"  },
  { id: 683, slug: "aromatisse",             nomFr: "Cocotine",                            forme: "base"     },
  { id: 685, slug: "slurpuff",               nomFr: "Cupcanaille",                         forme: "base"     },
  { id: 693, slug: "clawitzer",              nomFr: "Gamblast",                            forme: "base"     },
  { id: 695, slug: "heliolisk",              nomFr: "Iguolta",                             forme: "base"     },
  { id: 697, slug: "tyrantrum",              nomFr: "Rexillius",                           forme: "base"     },
  { id: 699, slug: "aurorus",                nomFr: "Dragmara",                            forme: "base"     },
  { id: 700, slug: "sylveon",                nomFr: "Nymphali",                            forme: "base"     },
  { id: 701, slug: "hawlucha",               nomFr: "Brutalibré",                          forme: "base"     },
  { id: 701, slug: "hawlucha-mega",          nomFr: "Méga-Brutalibré",                     forme: "mega"     },
  { id: 702, slug: "dedenne",                nomFr: "Dedenne",                             forme: "base"     },
  { id: 706, slug: "goodra",                 nomFr: "Muplodocus",                          forme: "base"     },
  { id: 706, slug: "goodra-hisui",           nomFr: "Muplodocus Forme de Hisui",           forme: "regional" },
  { id: 707, slug: "klefki",                 nomFr: "Trousselin",                          forme: "base"     },
  { id: 709, slug: "trevenant",              nomFr: "Desséliande",                         forme: "base"     },
  { id: 711, slug: "gourgeist-small",        nomFr: "Banshitrouye Variété Petite",         forme: "base"     },
  { id: 711, slug: "gourgeist",              nomFr: "Banshitrouye Variété Moyenne",        forme: "special"  },
  { id: 711, slug: "gourgeist-large",        nomFr: "Banshitrouye Variété Grande",         forme: "special"  },
  { id: 711, slug: "gourgeist-super",        nomFr: "Banshitrouye Variété Giga",           forme: "special"  },
  { id: 713, slug: "avalugg",                nomFr: "Séracrawl",                           forme: "base"     },
  { id: 713, slug: "avalugg-hisui",          nomFr: "Séracrawl Forme de Hisui",            forme: "regional" },
  { id: 715, slug: "noivern",                nomFr: "Bruyverne",                           forme: "base"     },
  // --- Génération 7 ---
  { id: 724, slug: "decidueye",              nomFr: "Archéduc",                            forme: "base"     },
  { id: 724, slug: "decidueye-hisui",        nomFr: "Archéduc Forme de Hisui",             forme: "regional" },
  { id: 727, slug: "incineroar",             nomFr: "Félinferno",                          forme: "base"     },
  { id: 730, slug: "primarina",              nomFr: "Oratoria",                            forme: "base"     },
  { id: 733, slug: "toucannon",              nomFr: "Bazoucan",                            forme: "base"     },
  { id: 740, slug: "crabominable",           nomFr: "Crabominable",                        forme: "base"     },
  { id: 740, slug: "crabominable-mega",      nomFr: "Méga-Crabominable",                   forme: "mega"     },
  { id: 745, slug: "lycanroc",               nomFr: "Lougaroc Forme Diurne",               forme: "base"     },
  { id: 745, slug: "lycanroc-midnight",      nomFr: "Lougaroc Forme Nocturne",             forme: "special"  },
  { id: 745, slug: "lycanroc-dusk",          nomFr: "Lougaroc Forme Crépusculaire",        forme: "special"  },
  { id: 748, slug: "toxapex",                nomFr: "Prédastérie",                         forme: "base"     },
  { id: 750, slug: "mudsdale",               nomFr: "Bourrinos",                           forme: "base"     },
  { id: 752, slug: "araquanid",              nomFr: "Tarenbulle",                          forme: "base"     },
  { id: 758, slug: "salazzle",               nomFr: "Malamandre",                          forme: "base"     },
  { id: 763, slug: "tsareena",               nomFr: "Sucreine",                            forme: "base"     },
  { id: 765, slug: "oranguru",               nomFr: "Gouroutan",                           forme: "base"     },
  { id: 766, slug: "passimian",              nomFr: "Quartermac",                          forme: "base"     },
  { id: 778, slug: "mimikyu-disguised",      nomFr: "Mimiqui Forme Déguisée",              forme: "base"     },
  { id: 778, slug: "mimikyu-busted",         nomFr: "Mimiqui Forme Démasquée",             forme: "special"  },
  { id: 780, slug: "drampa",                 nomFr: "Draïeul",                             forme: "base"     },
  { id: 780, slug: "drampa-mega",            nomFr: "Méga-Draïeul",                        forme: "mega"     },
  { id: 784, slug: "kommo-o",                nomFr: "Ékaïser",                             forme: "base"     },
  // --- Génération 8 ---
  { id: 823, slug: "corviknight",            nomFr: "Corvaillus",                          forme: "base"     },
  { id: 841, slug: "flapple",                nomFr: "Pomdrapi",                            forme: "base"     },
  { id: 842, slug: "appletun",               nomFr: "Dratatin",                            forme: "base"     },
  { id: 844, slug: "sandaconda",             nomFr: "Dunaconda",                           forme: "base"     },
  { id: 855, slug: "polteageist",            nomFr: "Polthégeist Forme Contrefaçon",       forme: "base"     },
  { id: 855, slug: "polteageist-antique",    nomFr: "Polthégeist Forme Authentique",       forme: "special"  },
  { id: 858, slug: "hatterene",              nomFr: "Sorcilence",                          forme: "base"     },
  { id: 866, slug: "mr-rime",                nomFr: "M. Glaquette",                        forme: "base"     },
  { id: 867, slug: "runerigus",              nomFr: "Tutétékri",                           forme: "base"     },
  { id: 869, slug: "alcremie",               nomFr: "Charmilly Lait Vanille",              forme: "base"     },
  { id: 869, slug: "alcremie-ruby-cream",    nomFr: "Charmilly Lait Ruby",                 forme: "special"  },
  { id: 869, slug: "alcremie-matcha-cream",  nomFr: "Charmilly Lait Matcha",               forme: "special"  },
  { id: 869, slug: "alcremie-mint-cream",    nomFr: "Charmilly Lait Menthe",               forme: "special"  },
  { id: 869, slug: "alcremie-lemon-cream",   nomFr: "Charmilly Lait Citron",               forme: "special"  },
  { id: 869, slug: "alcremie-salted-cream",  nomFr: "Charmilly Lait Salé",                 forme: "special"  },
  { id: 869, slug: "alcremie-ruby-swirl",    nomFr: "Charmilly Mélange Ruby",              forme: "special"  },
  { id: 869, slug: "alcremie-caramel-swirl", nomFr: "Charmilly Mélange Caramel",           forme: "special"  },
  { id: 869, slug: "alcremie-rainbow-swirl", nomFr: "Charmilly Mélange Tricolore",         forme: "special"  },
  { id: 877, slug: "morpeko",                nomFr: "Morpeko Mode Rassasié",               forme: "base"     },
  { id: 877, slug: "morpeko-hangry",         nomFr: "Morpeko Mode Affamé",                 forme: "special"  },
  { id: 887, slug: "dragapult",              nomFr: "Lanssorien",                          forme: "base"     },
  // --- Pokémon de Hisui ---
  { id: 899, slug: "wyrdeer",                nomFr: "Cerbyllin",                           forme: "base"     },
  { id: 900, slug: "kleavor",                nomFr: "Hachécateur",                         forme: "base"     },
  { id: 902, slug: "basculegion-male",       nomFr: "Paragruel Mâle",                      forme: "base"     },
  { id: 902, slug: "basculegion-female",     nomFr: "Paragruel Femelle",                   forme: "special"  },
  { id: 903, slug: "sneasler",               nomFr: "Farfurex",                            forme: "base"     },
  // --- Génération 9 ---
  { id: 908, slug: "meowscarada",            nomFr: "Miascarade",                          forme: "base"     },
  { id: 911, slug: "skeledirge",             nomFr: "Flâmigator",                          forme: "base"     },
  { id: 914, slug: "quaquaval",              nomFr: "Palmaval",                            forme: "base"     },
  { id: 925, slug: "maushold-three",         nomFr: "Famignol Famille de Trois",           forme: "base"     },
  { id: 925, slug: "maushold",               nomFr: "Famignol Famille de Quatre",          forme: "special"  },
  { id: 934, slug: "garganacl",              nomFr: "Gigansel",                            forme: "base"     },
  { id: 936, slug: "armarouge",              nomFr: "Carmadura",                           forme: "base"     },
  { id: 937, slug: "ceruledge",              nomFr: "Malvalame",                           forme: "base"     },
  { id: 939, slug: "bellibolt",              nomFr: "Ampibidou",                           forme: "base"     },
  { id: 952, slug: "scovillain",             nomFr: "Scovilain",                           forme: "base"     },
  { id: 952, slug: "scovillain-mega",        nomFr: "Méga-Scovilain",                      forme: "mega"     },
  { id: 956, slug: "espathra",               nomFr: "Cléopsytra",                          forme: "base"     },
  { id: 959, slug: "tinkaton",               nomFr: "Forgelina",                           forme: "base"     },
  { id: 964, slug: "palafin-zero",           nomFr: "Superdofin Forme Ordinaire",          forme: "base"     },
  { id: 964, slug: "palafin",                nomFr: "Superdofin Forme Super",              forme: "special"  },
  { id: 968, slug: "orthworm",               nomFr: "Ferdeter",                            forme: "base"     },
  { id: 970, slug: "glimmora",               nomFr: "Floréclat",                           forme: "base"     },
  { id: 970, slug: "glimmora-mega",          nomFr: "Méga-Floréclat",                      forme: "mega"     },
  { id: 981, slug: "farigiraf",              nomFr: "Farigiraf",                           forme: "base"     },
  { id: 983, slug: "kingambit",              nomFr: "Scalpereur",                          forme: "base"     },
  { id: 1013, slug: "sinistcha",             nomFr: "Théffroyable Forme Médiocre",         forme: "base"     },
  { id: 1013, slug: "sinistcha-masterpiece", nomFr: "Théffroyable Forme Exceptionnelle",   forme: "special"  },
  { id: 1018, slug: "archaludon",            nomFr: "Pondralugon",                         forme: "base"     },
  { id: 1019, slug: "hydrapple",             nomFr: "Pomdorochi",                          forme: "base"     },
];

// ============================================================
// 2. TRADUCTION DES TYPES ANGLAIS → FRANÇAIS
//    Utilisée par index.js et team.js
//    Source unique : ne pas dupliquer dans les autres fichiers.
// ============================================================
function translateType(typeEn) {
  const map = {
    fire:     "Feu",      water:    "Eau",      grass:    "Plante",
    electric: "Électrik", psychic:  "Psy",      ice:      "Glace",
    dragon:   "Dragon",   dark:     "Ténèbres", fighting: "Combat",
    poison:   "Poison",   ground:   "Sol",      flying:   "Vol",
    bug:      "Insecte",  rock:     "Roche",    ghost:    "Spectre",
    steel:    "Acier",    normal:   "Normal",   fairy:    "Fée",
  };
  return map[typeEn] || typeEn;
}
